# Generated by Django 5.1.3 on 2024-11-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_category_art_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='status',
            field=models.CharField(choices=[('vailable', 'Available'), ('sold', 'Sold Out')], default='vailable', max_length=10),
        ),
    ]
